# Generated by Django 5.2.9 on 2025-12-19 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'customers',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('model_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'printer_models',
                'db_table': 'printer_model',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'purchases',
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'stores',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'vendors',
                'db_table': 'vendor',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.customer')),
            ],
            options={
                'verbose_name_plural': 'customer_addresses',
                'db_table': 'customer_address',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('printer_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.printermodel')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchase')),
            ],
            options={
                'verbose_name_plural': 'purchase_items',
                'db_table': 'purchase_item',
                'unique_together': {('purchase', 'printer_model')},
            },
        ),
        migrations.CreateModel(
            name='PrinterUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('status', models.CharField(choices=[('INSTORE', 'In-store'), ('RENTED', 'Rented'), ('SCRAPPED', 'Scrapped')], default='INSTORE', max_length=20)),
                ('customer_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_printer_units', to='api.customeraddress')),
                ('printer_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='api.printermodel')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_printer_units', to='api.purchaseitem')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_printer_units', to='api.store')),
            ],
            options={
                'verbose_name_plural': 'printer_units',
                'db_table': 'printer_unit',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('challan_date', models.DateField()),
                ('order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateField()),
                ('customer_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='api.customeraddress')),
            ],
            options={
                'verbose_name_plural': 'rentals',
                'db_table': 'rental',
            },
        ),
        migrations.CreateModel(
            name='RentalReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('challan_date', models.DateField()),
                ('order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateField()),
                ('customer_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_returns', to='api.customeraddress')),
            ],
            options={
                'verbose_name_plural': 'rental_returns',
                'db_table': 'rental_return',
            },
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_entries', to='api.printerunit')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.rental')),
            ],
            options={
                'verbose_name_plural': 'rental_units',
                'db_table': 'rental_unit',
            },
        ),
        migrations.CreateModel(
            name='RentalReturnUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrapped', models.BooleanField(default=False)),
                ('printer_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_entries', to='api.printerunit')),
                ('rental_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_units', to='api.rentalreturn')),
                ('destination_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.store')),
            ],
            options={
                'verbose_name_plural': 'rental_return_units',
                'db_table': 'rental_return_unit',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='api.store'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='api.vendor'),
        ),
    ]
