# Generated by Django 5.2.9 on 2025-12-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='api.store'),
            preserve_default=False,
        ),
    ]
