# Generated by Django 5.2.9 on 2025-12-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rental_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalreturnunit',
            name='destination_store',
        ),
        migrations.AddField(
            model_name='rentalreturn',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='rental_returns', to='api.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalreturnunit',
            name='printer_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_return_entries', to='api.printerunit'),
        ),
        migrations.AlterField(
            model_name='rentalreturnunit',
            name='rental_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_returned_units', to='api.rentalreturn'),
        ),
    ]
