# Generated by Django 5.2.9 on 2025-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_rentalreturnunit_destination_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalreturn',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
