# Generated by Django 5.2.9 on 2026-01-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rentalreturn_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printermodel',
            name='model_number',
        ),
    ]
