# Generated by Django 5.2.9 on 2026-01-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_printermodel_model_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
